include:
  - board: xiao_ble//zmk        # ou o board real usado no Flake
    shield: anywhy_flake_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_USB=n

  - board: xiao_ble//zmk
    shield: anywhy_flake_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_USB=n

  - board: xiao_ble//zmk
    shield: settings_reset

  - board: xiao_ble//zmk  # ou xiao_ble//zmk, conforme a branch do YADS
    shield: flake_dongle dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: xiao_ble//zmk
    shield: settings_reset