# Ativa o suporte a WPM e Studio no ZMK se desejado
CONFIG_ZMK_WPM=y
CONFIG_ZMK_STUDIO=y

# Gerenciamento de energia (Dongle sempre ligado)
CONFIG_ZMK_SLEEP=n

CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80

CONFIG_PROSPECTOR_ANIMATION_WPM_REFERENCE=100
CONFIG_PROSPECTOR_ANIMATION_INTENSITY_DECAY_SEC=5
CONFIG_PROSPECTOR_ANIMATION_FLOW_DECAY_SEC=15

CONFIG_PROSPECTOR_SHOW_MODIFIERS=y