# --- Dongle sempre alimentado na USB ---
CONFIG_ZMK_SLEEP=n

# --- Nomes das Camadas e Cativador de WPM ---
CONFIG_ZMK_KEYMAP_LAYER_NAME=y
CONFIG_ZMK_WPM=y

# --- Widgets do Display (janpfischer / zmk-dongle-screen) ---
CONFIG_DONGLE_SCREEN_WPM_WIDGET=y
CONFIG_DONGLE_SCREEN_MOD_WIDGET=y
CONFIG_DONGLE_SCREEN_LAYER_WIDGET=y
CONFIG_DONGLE_SCREEN_BATTERY_WIDGET=y

# --- Leitura da Bateria dos Periféricos ---
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y